# This is a basic workflow to help you get started with Actions

name: CI Build Ort DML

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]
    name: Python ${{ matrix.python-version }} sample

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install visualstudio2017buildtools
        run: choco install visualstudio2017buildtools
          
      - name: Get specific version CMake, v3.18.4
        run: choco install cmake --version=3.18.4
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: "v1.8.1"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          .\build.bat --config RelWithDebInfo --build_shared_lib --parallel
