# File: .github/workflows/repo-sync.yml

name: Repo-Sync

on:
  schedule:
  - cron:  '30 5,17 * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/microsoft/onnxruntime"
        source_branch: ""
        destination_branch: ""
        github_token: ${{ secrets.PAT }}
        sync_tags: true
